#!/usr/bin/env python
#
# This file is part of rtn-114
#
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Script for generating the various latex parameters referred to in the AP
# paper.

# Contact Authors: Eric Bellm, Ian Sullivan

import csv
import numpy as np

# Function to round to N significant figures
def round_sf(x, sig=3):
    return np.round(x, sig - int(np.floor(np.log10(abs(x)))) - 1)

def formatParameter(params, name):
    '''
    Formats a named parameter ready for write-out to tex file.
    '''

    value = params[0][name]
    if isinstance(value, float):
        value = f'{value:.3f}'.rstrip('0').rstrip('.')

    if name in params[1]:
        unit = params[1][name]
        if unit[0:7] not in ['\\arcsec', '\\arcmin', '\\degree']:
            unit = f'\\xspace {unit}'
        else:
            if '.' in value:
                match unit[0:7]:
                    case '\\arcsec':
                        value = value.replace('.','\\farcs')
                        unit = unit.replace('\\arcsec', '')
                    case '\\arcmin':
                        value = value.replace('.','\\farcm')
                        unit = unit.replace('\\arcmin', '')
                    case '\\degree':
                        value = value.replace('.','\\fdg')
                        unit = unit.replace('\\degree', '')
    else:
        unit = ''

    return f'\\newcommand{{\\{name}}}{{{value}{unit}\\xspace}}\n'

def addParameter(params, name, value, unit=None, **kwargs):

    '''
    Adds a named parameter to the params tuple of dictionaries.

    Ensures that the namings between the values and units
    dictionaries are consistent.
    '''
    if 'sig' in kwargs:
        value = round_sf(value, **kwargs)

    params[0][name] = value
    if unit:
        params[1][name] = unit

    return params


#-------- Manually added parameters --------#
# A small number of parameters cannot be readily generated autimatically.
# These are kept in the manualParameters.csv file.
def manualParameters(params):
    print('Adding manual parameters...')
    with open('../manualParameters.csv', newline='') as f:
        reader = csv.reader(f, delimiter=',')
        for line in reader:
            if line[2] == '':
                line[2]=None
            params = addParameter(params, line[0], line[1], unit=line[2])

    return params

if __name__ == "__main__":

    params = (dict(), dict())

    # Using functions allows for easier debugging.
    params = manualParameters(params)


    #-------- Write the parameters to file --------#
    boilerPlate = '''% These parameters are automatically generated by scripts/ap_parameters.py.
% Do NOT manually edit this file.
% If you need to change/add a parameter, please edit the ap_parameters.py script and re-run it as a
% command-line executable.
% If you need to manually add a parameter because it can't be readily generated from data (such as a url)
% then please add it to the manualParameters.csv file.\n
'''
    with open("../parameters.tex", "w") as f:
        f.write(boilerPlate)
        for name in params[0]:
            f.write(formatParameter(params, name))
    f.close()
